### ISSUE TITLE
Implementar item para usar o comando

### ISSUE THREAD

**Issue by CMDTelhada** [Skerverus/esx_arrombar#2]
Para usar o comando o player ter item lockpick que deve ser comprado para que ele consiga arrombar veiculo.

**Comment by MichelSchiavo** [comment]
Eu fiz pensando em justamente não precisar de um item e ficar mais fácil de usar por não precisar abrir inventário, mas acho que este item já exista na profissão do mecânico, colocar para vender em uma loja.
